### ISSUE TITLE
[Feature Request] Resolve prediction if you reach split X.

### ISSUE THREAD

**Issue by Urotsuki1** [Marenthyu/LiveSplit.StreamingPredictionsComponent#5]
"Resolve prediction when the following text is in the current split"
This allows for predictions of the type "Run will make it to split X (regardless of time)".

**Comment by Marenthyu** [comment]
This should be easy enough to implement!
I'll most likely re-do the Settings UI a bit to allow for a more easy choice between when what action happens, there this can be included.

**Comment by Marenthyu** [comment]
Implemented, will be available in Version 2.0
